# -*- coding: utf-8 -*-
"""Auto Insurance in Sweden.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lfp44ofWhz3uXGwiNwgBQGiKRJYYBMPe
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_csv("Auto Insurance in Sweden 2.csv")
X = data.iloc[:, :1].values
y = data.iloc[:, -1].values

print(X)

print(y)

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X,y)

regressor.predict([[45]])

X_grid = np.arange(min(X), max(X), 0.5)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, color='blue')
plt.plot(X_grid, regressor.predict(X_grid), color='red')
plt.title("Auto Insurance in Sweden")
plt.xlabel("number of claims")
plt.ylabel("total payment for all the claims in thousands of Swedish Kronor")
plt.show()